# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 140a3bccae0303bd2bdf39fa331bfcd488d61e2a18284dc9f16d5e5174d24923ce915353392c4062e111e47124bd77d07c35901712a7617353a76d6fadd1dd9c

test:
  secret_key_base: 3b663068c299a9b8c445a27e511449d1469be362857eb63dc52761229f961670d398920060ea5bc15ba6f1f7865ac78bece872c020238317551492f27eccb06b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
